name: CodiumAI PR-Agent

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Codium-ai/pr-agent@v1.3.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
