name: Remote Update and Deploy

on:
  push:
    branches:
      - main

jobs:
  remote-update-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.3' # أو أي نسخة تحتاجها

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ve-shop.co/ve-shop/ve-shop-frontend
            git pull origin main
            npm install
            npm run build
            npm run deploy
            echo "Deployment completed successfully."
          timeout: 3m
          command_timeout: 15m
          debug: true
