name: Remote Update and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.3'

      - name: Install dependencies (Frontend)
        working-directory: ./ve-shop-frontend
        run: npm install

      - name: Build Frontend
        working-directory: ./ve-shop-frontend
        run: npm run build

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /home/ve-shop.co/ve-shop/
            git pull origin main
            cd ve-shop-frontend
            npm install
            npm run build
            npm run deploy
            echo "Deployment completed successfully."
          timeout: 3m
          command_timeout: 15m
          debug: true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ve-shop-frontend/dist  # أو غيّر حسب اسم مجلد build عندك
