- name: Deploy to VPS via SSH
  uses: appleboy/ssh-action@v0.1.10
  with:
    host: ${{ secrets.VPS_HOST }}
    username: root
    key: ${{ secrets.VPS_PRIVATE_KEY }}
    port: 22
    script: |
      cd /home/ve-shop.co/ve-shop/ve-shop-frontend
      echo "Starting remote deployment on ve-frontend..."
      git stash --include-untracked
      git pull origin main
      [ -f package-lock.json ] && rm package-lock.json
      [ -d node_modules ] && rm -rf node_modules
      npm install
      echo "npm dependencies installed."
      npm run build
      if [ -d "dist" ] && [ "$(ls -A dist)" ]; then
        echo "Build successful!"
        npm run deploy
      else
        echo "deploy failed!"
        exit 1
      fi
      echo "Deployment completed successfully."
    timeout: 3m
    command_timeout: 15m
    debug: true
